#!/bin/sh

directory="/var/tmp/libraries/"
update () { svn checkout --non-interactive --quiet https://svn.inf.ethz.ch/svn/lecturers/a2/trunk/tools/builds/a2 "$directory" && svn checkout --non-interactive --quiet https://svn.inf.ethz.ch/svn/lecturers/a2/trunk/ocp/Matrix "$directory/Matrix" && make --directory "$directory" --quiet dependencies && version="$(svnversion "$directory/source")"; }
check () { make --question --directory "$directory" --makefile=Matrix/test --quiet "$target"; }
build () { timeout 1h make --directory "$directory" --makefile=Matrix/test --quiet "$target"; }
notify () { echo "$output" | sendbuild "Libraries" "$target" "$version" "$status"; }

update || exit 1

process ()
{
	local target="$1"
	check && exit 0
	local status="Building" output=""
	notify
	trap notify exit
	trap "status=Aborted" int term kill
	status="Failed" output=$(build 2>&1)
	test $? -eq 0 && status="Succeeded"
	trap exit
	notify
}

process "Matrix Library"
