#

CC=gcc  -m32
CFLAGS  = -DSOLARIS
LDFLAGS = -lthread -lX11 -ldl -lrt -lm

all:	aos.solaris 
	rm -f *.o

aos.solaris:	aos.o Threads.solaris.o
	$(CC) -s -o aos.solaris aos.o Threads.solaris.o $(LDFLAGS)

aos.o:	aos.c
	$(CC) -c $(CFLAGS) aos.c

Threads.solaris.o:	Threads.h Threads.solaris.c
	$(CC) -c $(CFLAGS) Threads.solaris.c 


